# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('realname', models.CharField(default='无', max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('operate_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
