# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20181207_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(default='公共', on_delete=django.db.models.deletion.CASCADE, to='backweb.Column'),
        ),
    ]
